In [1]:
# Importamos Pandas para trabajar con dataframes
import pandas as pd

In [2]:
# Importamos los archivos CSV, uno para cada servicio de streaming
Amazon = pd.read_csv("Datasets/amazon_prime_titles-score.csv")
Disney = pd.read_csv("Datasets/disney_plus_titles-score.csv")
Hulu = pd.read_csv("Datasets/hulu_titles-score (2).csv")
Netflix = pd.read_csv("Datasets/netflix_titles-score.csv")

In [3]:
# Verificamos la importaciòn correcta de los datasets
Amazon.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...,99
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,37
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,20
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ...",27
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,75

In [4]:
Disney.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!,100
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...,17
2,s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,TV-G,23 min,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.,92
3,s4,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",NaN,"November 26, 2021",2021,TV-PG,41 min,Musical,"This is real life, not just fantasy!",35
4,s5,TV Show,The Beatles: Get Back,NaN,"John Lennon, Paul McCartney, George Harrison, ...",NaN,"November 25, 2021",2021,NaN,1 Season,"Docuseries, Historical, Music",A three-part documentary from Peter Jackson ca...,11

In [5]:
Hulu.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score
0,s1,Movie,Ricky Velez: Here's Everything,NaN,NaN,NaN,"October 24, 2021",2021,TV-MA,NaN,"Comedy, Stand Up",​Comedian Ricky Velez bares it all with his ho...,48
1,s2,Movie,Silent Night,NaN,NaN,NaN,"October 23, 2021",2020,NaN,94 min,"Crime, Drama, Thriller","Mark, a low end South London hitman recently r...",8
2,s3,Movie,The Marksman,NaN,NaN,NaN,"October 23, 2021",2021,PG-13,108 min,"Action, Thriller",A hardened Arizona rancher tries to protect an...,8
3,s4,Movie,Gaia,NaN,NaN,NaN,"October 22, 2021",2021,R,97 min,Horror,A forest ranger and two survivalists with a cu...,33
4,s5,Movie,Settlers,NaN,NaN,NaN,"October 22, 2021",2021,NaN,104 min,"Science Fiction, Thriller",Mankind's earliest settlers on the Martian fro...,24

In [6]:
Netflix.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",20
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",8
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,55
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",7
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,44

In [7]:
# Generamos el campo id: Cada id se compondrá de la primera letra del
# nombre de la plataforma, seguido del show_id ya presente en los
# datasets (ejemplo para títulos de Amazon = as123)
Amazon.insert(loc=0, column="id", value="a" + Amazon["show_id"])
Disney.insert(loc=0, column="id", value="d" + Disney["show_id"])
Hulu.insert(loc=0, column="id", value="h" + Hulu["show_id"])
Netflix.insert(loc=0, column="id", value="n" + Netflix["show_id"])

In [30]:
# Comprobamos la correcta inserciòn del nuevo campo
Netflix.head()

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score
0,ns1,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",29
1,ns2,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",86
2,ns3,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,75
3,ns4,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",49
4,ns5,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,92

In [ ]:
# Juntamos todos los datasets en uno solo, ya que contamos
# con el campo id para diferenciar el servicio, y las
# transformaciones a continuación se aplican a todos por igual
moviesdb = Amazon.append(Disney).append(Hulu).append(Netflix)

In [32]:
# Verificamos el resultado
moviesdb.head()

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score
0,as1,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...,99
1,as2,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,37
2,as3,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,20
3,as4,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ...",27
4,as5,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,75

In [11]:
moviesdb.tail()

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score
8802,ns8803,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",20
8803,ns8804,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",8
8804,ns8805,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,55
8805,ns8806,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",7
8806,ns8807,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,44

In [33]:
# Verificamos existencia y cantidad de nulos por columna en el dataframe
moviesdb.isnull().sum()

id                  0
show_id             0
type                0
title               0
director         8259
cast             5321
country         11499
date_added       9554
release_year        0
rating            864
duration          482
listed_in           0
description         4
score               0
dtype: int64

In [34]:
# Reemplazamos los valores nulos del campo "Rating" por la letra "G"
# (corresponde al maturity rating "General por all audiences")
moviesdb["rating"].fillna("G", inplace=True)

In [35]:
# Controlamos la correcciòn sobre la columna "rating"
moviesdb.isnull().sum()

id                  0
show_id             0
type                0
title               0
director         8259
cast             5321
country         11499
date_added       9554
release_year        0
rating              0
duration          482
listed_in           0
description         4
score               0
dtype: int64

In [37]:
# Visualizamos el dataframe modificado
moviesdb.head()

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score
0,as1,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,G,113 min,"Comedy, Drama",A small fishing village must procure a local d...,99
1,as2,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...,37
2,as3,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,G,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...,20
3,as4,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,G,69 min,Documentary,"Pink breaks the mold once again, bringing her ...",27
4,as5,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,G,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...,75

In [38]:
# Cambiamos el formato de la columna "date_added" a AAAA-mm-dd
moviesdb["date_added"] = pd.to_datetime(moviesdb["date_added"])

In [39]:
# Verificamos
moviesdb.tail()

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score
8802,ns8803,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2019-11-20,2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",20
8803,ns8804,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,2019-07-01,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",8
8804,ns8805,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2019-11-01,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,55
8805,ns8806,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2020-01-11,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",7
8806,ns8807,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,44

In [40]:
# Pasamos a minúsculas los campos de texto
moviesdb["type"] = moviesdb["type"].str.lower()
moviesdb["title"] = moviesdb["title"].str.lower()
moviesdb["director"] = moviesdb["director"].str.lower()
moviesdb["cast"] = moviesdb["cast"].str.lower()
moviesdb["country"] = moviesdb["country"].str.lower()
moviesdb["rating"] = moviesdb["rating"].str.lower()
moviesdb["duration"] = moviesdb["duration"].str.lower()
moviesdb["listed_in"] = moviesdb["listed_in"].str.lower()
moviesdb["description"] = moviesdb["description"].str.lower()

In [19]:
# Verificamos
moviesdb.head()

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score
0,as1,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,113 min,"comedy, drama",a small fishing village must procure a local d...,99
1,as2,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30,2018,13+,110 min,"drama, international",a metro family decides to fight a cyber crimin...,37
2,as3,s3,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2021-03-30,2017,g,74 min,"action, drama, suspense",after a man discovers his wife is cheating on ...,20
3,as4,s4,movie,pink: staying true,sonia anderson,"interviews with: pink, adele, beyoncé, britney...",united states,2021-03-30,2014,g,69 min,documentary,"pink breaks the mold once again, bringing her ...",27
4,as5,s5,movie,monster maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,2021-03-30,1989,g,45 min,"drama, fantasy",teenage matt banting wants to work with a famo...,75

In [20]:
# Separamos el campo "duration" en 2 columnas
splitcolumns = moviesdb["duration"].str.split(" ", n=1, expand=True)

In [21]:
# Insertamos una columna con las cantidades
moviesdb["duration_int"] = splitcolumns[0]

In [41]:
# Insertamos una columna con la unidad de medición
moviesdb["duration_type"] = splitcolumns[1]

In [23]:
# Reemplazamos "seasons" por "season" en la columna "duration_type"
moviesdb["duration_type"] = moviesdb["duration_type"].str.replace("seasons", "season")

In [24]:
# Cambiamor el formato del campo "duration_int" a integer
moviesdb["duration_int"] = moviesdb["duration_int"].astype("Int64")

In [42]:
# Verificamos
moviesdb.head(10)

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,score,duration_type
0,as1,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021-03-30,2014,g,113 min,"comedy, drama",a small fishing village must procure a local d...,99,min
1,as2,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021-03-30,2018,13+,110 min,"drama, international",a metro family decides to fight a cyber crimin...,37,min
2,as3,s3,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2021-03-30,2017,g,74 min,"action, drama, suspense",after a man discovers his wife is cheating on ...,20,min
3,as4,s4,movie,pink: staying true,sonia anderson,"interviews with: pink, adele, beyoncé, britney...",united states,2021-03-30,2014,g,69 min,documentary,"pink breaks the mold once again, bringing her ...",27,min
4,as5,s5,movie,monster maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,2021-03-30,1989,g,45 min,"drama, fantasy",teenage matt banting wants to work with a famo...,75,min
5,as6,s6,movie,living with dinosaurs,paul weiland,"gregory chisholm, juliet stevenson, brian hens...",united kingdom,2021-03-30,1989,g,52 min,"fantasy, kids",the story unfolds in a an english seaside town...,74,min
6,as7,s7,movie,hired gun,fran strine,"alice cooper, liberty devitto, ray parker jr.,...",united states,2021-03-30,2017,g,98 min,"documentary, special interest","they are the ""first call, a-list"" musicians, j...",50,min
7,as8,s8,movie,grease live!,"thomas kail, alex rudzinski","julianne hough, aaron tveit, vanessa hudgens, ...",united states,2021-03-30,2016,g,131 min,comedy,"this honest, uncompromising comedy chronicles ...",84,min
8,as9,s9,movie,global meltdown,daniel gilboy,"michael paré, leanne khol young, patrick j. ma...",canada,2021-03-30,2017,g,87 min,"action, science fiction, suspense",a helicopter pilot and an environmental scient...,46,min
9,as10,s10,movie,david's mother,robert allan ackerman,"kirstie alley, sam waterston, stockard channing",united states,2021-04-01,1994,g,92 min,drama,sally goodson is a devoted mother to her autis...,70,min

In [43]:
moviesdb.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22998 entries, 0 to 8806
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             22998 non-null  object
 1   show_id        22998 non-null  object
 2   type           22998 non-null  object
 3   title          22998 non-null  object
 4   director       14739 non-null  object
 5   cast           17677 non-null  object
 6   country        11499 non-null  object
 7   date_added     13444 non-null  datetime64[ns]
 8   release_year   22998 non-null  int64
 9   rating         22998 non-null  object
 10  duration       22516 non-null  object
 11  listed_in      22998 non-null  object
 12  description    22994 non-null  object
 13  score          22998 non-null  int64
 14  duration_type  22998 non-null  object
dtypes: datetime64[ns](1), int64(2), object(12)
memory usage: 2.8+ MB

In [27]:
# Exportamos el dataframe para ser utilizado por la API
moviesdb.to_csv("movies_database.csv", index=False)